name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 0 * * *'   # Midnight UTC
    - cron: '0 6 * * *'   # 6 AM UTC
    - cron: '0 12 * * *'  # Noon UTC
    - cron: '0 18 * * *'  # 6 PM UTC
  workflow_dispatch:       # Allows manual trigger from GitHub

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit app
        run: curl -I https://fatboard.streamlit.app
