name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */2 * * *'   # Every 2 hours at minute 0
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit app
        run: curl -I https://fatboard.streamlit.app
